openapi: 3.0.1
info:
  title: Order Service
  description: The order service where it is powered by Queues, this web service is only here for reading the services persistence state
  version: 0.1.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  '/order/{orderId}':
    get:
      tags:
        - orderId
      summary: returns an order
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: The id of the order placed
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An order object placed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Not found

components:
  schemas:
    Order:
      type: object
      properties:
        orderEntries:
          type: array
          items:
            $ref: '#/components/schemas/OrderEntry'
        orderId:
          type: string
        totalCost:
          type: string
    OrderEntry:
      type: object
      properties:
        productId:
          type: string
        amount:
          type: integer
        unitCost:
          type: string
